### ISSUE TITLE
Animation : image reveal on hover

### ISSUE THREAD

**Issue by szkjn** [szkjn/hybrida_fest_website#9]

**Comment by jimblu** [comment]
Super TUTO for reveal on hover on[CODROPS](https://tympanus.net/codrops/2020/07/01/creating-a-menu-image-animation-on-hover/) and the [DEMO](https://tympanus.net/Tutorials/RapidImageHoverMenu/) and [GITHUB](https://github.com/codrops/RapidImageHoverMenu/)
5 [DEMO](https://tympanus.net/Development/RapidImageHoverMenuEffects/index5.html) from the same website and the [GITHUB](https://github.com/codrops/RapidImageHoverMenuEffects/) 
@szkjn

**Comment by jimblu** [comment]
new inspiration : [photos all screen](https://tympanus.net/Development/FullscreenHoverLoop/)
@szkjn
